name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Test with Pytest
      run: python setup.py pytest
      env:
              TOKEN: ${{ secrets.TOKEN }}
              CHANNEL: ${{ secrets.CHANNEL }}
